version: '3.9'

services:
    psql_db:
        image: postgres:15
        container_name: matchmaker-db
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        ports:
            - "${DB_PORT}:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

    api:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: matchmaker-api
        ports:
            - "${APP_PORT}:${APP_PORT}"
        env_file:
            - .env
        depends_on:
            - psql_db

volumes:
    pgdata:
