name: Go CI

on:
    push:
        branches:
            - '**'
    pull_request:
        branches:
            - '**'

jobs:
    #    build-and-test:
    #        name: Build & Test
    #        runs-on: ubuntu-latest

    #        steps:
    #            -   name: Checkout code
    #                uses: actions/checkout@v4
    #
    #            -   name: Set up Go
    #                uses: actions/setup-go@v5
    #                with:
    #                    go-version: '1.22'
    #
    #            -   name: Install dependencies
    #                run: go mod tidy
    #
    #            -   name: Build
    #                run: go build ./...
    #
    #            -   name: Run tests
    #                run: go test ./...
    #
    #            -   name: Static analysis (go vet)
    #                run: go vet ./...
    
    dummy:
        runs-on: ubuntu-latest
        steps:
            -   name: Always succeed
                run: echo "CI dummy run successful" && true
