name: dummy

on:
    push:
        branches: [ '**' ]
    pull_request:
        branches: [ '**' ]

jobs:
    dummy:
        runs-on: ubuntu-latest
        steps:
            - name: Always succeed
              run: echo "Dummy check" && true
