name: Go CI

on:
    push:
        branches: ['**']
    pull_request:
        branches: ['**']

jobs:
    build-only:
        # Build the Go binary on every push or pull request
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-go@v5
              with:
                  go-version: '1.22'

            - name: Tidy & build
              run: |
                  make tidy
                  make build

    docker-build:
        # Build the container *only* when pushing to main or tagging a release
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v')
        needs: build-only
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Build Docker image
              run: make docker-build
